version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_local
    environment:
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepassword
      POSTGRES_DB: sampledatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: django_local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/public/static
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume: